llm:
  # For easier testing
  enabled: True

tts:
  use_gpu: True
  model_name: 'tts_models/multilingual/multi-dataset/xtts_v2'
  vocoder_name: 'vocoder_models/en/ljspeech/hifigan_v2'
  chunk_size: 0

  # Required for multispeaker models (like xtts_v2)
  # Call `make xtts-list-speakers` to get speakers.
  # Then pick one at random.
  #
  # Or `xtts-create-speaker-samples` to generate samples
  # so you can manually pick pick best one.
  speaker: 'Rosemary Okafor'

  # Required in multilingual models (like xtts_v2)
  language: 'en'

  # Optional file that contains voice we will be cloning
  # sample_of_cloned_voice_wav: 'voice_to_clone.wav'
